apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    chartVersion: {{ .Chart.Version }}
data:
  App.config: {{ .Values.config | toYaml | indent 1 }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.global.project_name }}-{{ .Values.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    chartVersion: {{ .Chart.Version }}
spec:
  schedule: "{{ .Values.cron_schedule }}"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            redis-client: "{{ .Values.isRedisClient }}"
        spec:
          volumes:
          - name: {{ .Values.name }}-config-volume
            configMap:
              name: {{ .Values.name }}-config
          imagePullSecrets:
          - name: {{ .Values.global.project_name }}-dockerhub-registry-key
          containers:
          - image: {{ .Values.global.repository }}/{{ .Values.image }}:{{ .Values.tag }}
            name: {{ .Values.global.project_name }}-{{ .Values.name }}
            imagePullPolicy: Always
            {{- if .Values.resourceLimitation }}
            resources:
              limits:
                cpu: {{ .Values.resources.limits.cpu }}
                memory: {{ .Values.resources.limits.memory }}
              requests:
                cpu: {{ .Values.resources.requests.cpu }}
                memory: {{ .Values.resources.requests.memory }}
            {{- end }}
            env:
            - name: CURRENT_CRON_SCHEDULE
              value: "{{ .Values.cron_schedule }}"
            volumeMounts:
            - name: {{ .Values.name }}-config-volume
              mountPath: /app/App.config
              subPath: App.config
            - name: {{ .Values.name }}-config-volume
              mountPath: /app/{{ .Values.cron_dll }}
              subPath: App.config
          restartPolicy: OnFailure
