using System;
using SmartrTools;
using System.Diagnostics;
using System.Configuration;
using System.Threading.Tasks;

namespace BLC
{
    public partial class BLC
    {
        #region StopWatch properties
        public Stopwatch _Execution_Time_Get_Kpi_By_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_ASSET_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Ext_study_zone_By_EXT_STUDY_ZONE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_KPI_USER_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_KPI_USER_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_KPI_USER_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_SETUP_CATEGORY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_SPACE_ASSET_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_FLOOR_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_KPI_USER_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_SPACE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_ASSET_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_KPI_USER_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_KPI_USER_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_KPI_USER_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_SPACE_ASSET_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_FLOOR_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_KPI_USER_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_SPACE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_SITE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_ASSET_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Ext_study_zone_By_EXT_STUDY_ZONE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_KPI_USER_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_KPI_USER_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_KPI_USER_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_SETUP_CATEGORY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_SPACE_ASSET_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_FLOOR_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_KPI_USER_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_SPACE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_SITE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_ASSET_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_KPI_USER_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_KPI_USER_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_KPI_USER_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_SPACE_ASSET_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_FLOOR_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_KPI_USER_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_SPACE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_SITE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_DIMENSION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_SETUP_CATEGORY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_MIN_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_MAX_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_KPI_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_ASSET_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Ext_study_zone_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Ext_study_zone_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_SETUP_CATEGORY_NAME_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_VALUE { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_SPACE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_ASSET_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_EXTERNAL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_IS_MERAKI_WIFI_SIGNAL { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_DATA_SOURCE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USERNAME_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_EMAIL_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_IS_RECEIVE_EMAIL { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_IS_ACTIVE_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_FLOOR_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_DIMENSION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_SETUP_CATEGORY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_MIN_DATA_LEVEL_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_MAX_DATA_LEVEL_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_KPI_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_ASSET_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_SITE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_TOP_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_TOP_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_VALUE_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_SPACE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_ASSET_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_EXTERNAL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_IS_MERAKI_WIFI_SIGNAL_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_TOP_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_DATA_SOURCE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_ORGANIZATION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_ENTITY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USERNAME_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_EMAIL_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_ORGANIZATION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_IS_RECEIVE_EMAIL_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_IS_ACTIVE_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_FLOOR_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_TOP_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_DIMENSION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_SETUP_CATEGORY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_MIN_DATA_LEVEL_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_MAX_DATA_LEVEL_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_KPI_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_ASSET_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_SITE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_SPACE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_ASSET_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_DATA_SOURCE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_ORGANIZATION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_ENTITY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_ORGANIZATION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_FLOOR_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_DIMENSION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_SETUP_CATEGORY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_MIN_DATA_LEVEL_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_MAX_DATA_LEVEL_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_KPI_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_ASSET_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_SITE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_TOP_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_TOP_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_SPACE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_ASSET_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_TOP_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_DATA_SOURCE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_ORGANIZATION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_ENTITY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_ORGANIZATION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_FLOOR_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_TOP_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Ext_study_zone_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Asset_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_asset_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_data_source_kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Space_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Delete_Kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_Asset { get; set; }
        public Stopwatch _Execution_Time_Delete_Ext_study_zone { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Delete_Area { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_category { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_asset { get; set; }
        public Stopwatch _Execution_Time_Delete_District { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_data_source_kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_Floor { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Delete_User { get; set; }
        public Stopwatch _Execution_Time_Delete_Space { get; set; }
        public Stopwatch _Execution_Time_Delete_Site { get; set; }
        public Stopwatch _Execution_Time_Delete_Kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Kpi_By_DIMENSION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Kpi_By_SETUP_CATEGORY_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Kpi_By_MIN_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Kpi_By_MAX_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Kpi_By_KPI_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Asset_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Asset_By_ASSET_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Asset_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Ext_study_zone_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Ext_study_zone_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_ENTITY_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_category_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_category_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_category_By_SETUP_CATEGORY_NAME_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_By_SETUP_CATEGORY_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_By_SETUP_CATEGORY_ID_VALUE { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_asset_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_asset_By_SPACE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_asset_By_ASSET_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_asset_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_asset_By_EXTERNAL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_asset_By_IS_MERAKI_WIFI_SIGNAL { get; set; }
        public Stopwatch _Execution_Time_Delete_District_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_District_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_data_source_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_data_source_kpi_By_DATA_SOURCE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_data_source_kpi_By_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_data_source_kpi_By_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_data_source_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Floor_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Floor_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Floor_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_USERNAME_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_EMAIL_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_USER_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_IS_RECEIVE_EMAIL { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_OWNER_ID_IS_ACTIVE_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_By_FLOOR_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Edit_Kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_Asset { get; set; }
        public Stopwatch _Execution_Time_Edit_Ext_study_zone { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity { get; set; }
        public Stopwatch _Execution_Time_Edit_District_kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Edit_Area { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_Setup_category { get; set; }
        public Stopwatch _Execution_Time_Edit_Setup { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_Space_asset { get; set; }
        public Stopwatch _Execution_Time_Edit_District { get; set; }
        public Stopwatch _Execution_Time_Edit_Organization_data_source_kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_Floor { get; set; }
        public Stopwatch _Execution_Time_Edit_District_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Edit_User { get; set; }
        public Stopwatch _Execution_Time_Edit_Space { get; set; }
        public Stopwatch _Execution_Time_Edit_Site { get; set; }
        public Stopwatch _Execution_Time_Edit_Kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Asset_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Ext_study_zone_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_kpi_user_access_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_kpi_user_access_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_List { get; set; }
        public Stopwatch _Execution_Time_Edit_District_kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_kpi_user_access_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Setup_category_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Setup_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Space_asset_List { get; set; }
        public Stopwatch _Execution_Time_Edit_District_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Organization_data_source_kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Floor_List { get; set; }
        public Stopwatch _Execution_Time_Edit_District_kpi_user_access_List { get; set; }
        public Stopwatch _Execution_Time_Edit_User_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Space_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_List { get; set; }
        public Stopwatch _Execution_Time_Get_Week_Of_Year { get; set; }
        public Stopwatch _Execution_Time_Get_GeoData_By_GEODATA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_GeoData_By_GEODATA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Latest_GeoData_By_KPI { get; set; }
        public Stopwatch _Execution_Time_Delete_GeoData_By_GEODATA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_GeoData_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Compute_District_Kpi_Data_Hourly { get; set; }
        public Stopwatch _Execution_Time_Compute_District_Kpi_Data_Daily { get; set; }
        public Stopwatch _Execution_Time_Compute_District_Kpi_Data_Weekly { get; set; }
        public Stopwatch _Execution_Time_Compute_District_Kpi_Data_Monthly { get; set; }
        public Stopwatch _Execution_Time_Edit_District_Kpi_Data_List_Unique_By_RECORD_DATE_KPI_ID_TIMESPAN { get; set; }
        public Stopwatch _Execution_Time_Insert_District_Kpi_Data_List { get; set; }
        public Stopwatch _Execution_Time_Delete_District_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Compute_Area_Kpi_Data_Hourly { get; set; }
        public Stopwatch _Execution_Time_Compute_Area_Kpi_Data_Daily { get; set; }
        public Stopwatch _Execution_Time_Compute_Area_Kpi_Data_Weekly { get; set; }
        public Stopwatch _Execution_Time_Compute_Area_Kpi_Data_Monthly { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_Kpi_Data_List_Unique_By_RECORD_DATE_KPI_ID_TIMESPAN { get; set; }
        public Stopwatch _Execution_Time_Insert_Area_Kpi_Data_List { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Compute_Site_Kpi_Data_Hourly { get; set; }
        public Stopwatch _Execution_Time_Compute_Site_Kpi_Data_Daily { get; set; }
        public Stopwatch _Execution_Time_Compute_Site_Kpi_Data_Weekly { get; set; }
        public Stopwatch _Execution_Time_Compute_Site_Kpi_Data_Monthly { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_Kpi_Data_List_Unique_By_RECORD_DATE_KPI_ID_TIMESPAN { get; set; }
        public Stopwatch _Execution_Time_Insert_Site_Kpi_Data_List { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_Incidents { get; set; }
        public Stopwatch _Execution_Time_Get_Incidents_By_ENTITY_ID_DIMENSION_ORDER { get; set; }
        public Stopwatch _Execution_Time_Compute_Entity_Kpi_Data_Hourly { get; set; }
        public Stopwatch _Execution_Time_Compute_Entity_Kpi_Data_Daily { get; set; }
        public Stopwatch _Execution_Time_Compute_Entity_Kpi_Data_Weekly { get; set; }
        public Stopwatch _Execution_Time_Compute_Entity_Kpi_Data_Monthly { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_Kpi_Data_List_Unique_By_RECORD_DATE_KPI_ID_TIMESPAN { get; set; }
        public Stopwatch _Execution_Time_Insert_Entity_Kpi_Data_List { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Compute_Floor_Kpi_Data_Hourly { get; set; }
        public Stopwatch _Execution_Time_Compute_Floor_Kpi_Data_Daily { get; set; }
        public Stopwatch _Execution_Time_Compute_Floor_Kpi_Data_Weekly { get; set; }
        public Stopwatch _Execution_Time_Compute_Floor_Kpi_Data_Monthly { get; set; }
        public Stopwatch _Execution_Time_Edit_Floor_Kpi_Data_List_Unique_By_RECORD_DATE_KPI_ID_TIMESPAN { get; set; }
        public Stopwatch _Execution_Time_Insert_Floor_Kpi_Data_List { get; set; }
        public Stopwatch _Execution_Time_Delete_Floor_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Space_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Compute_Space_Kpi_Data_Daily { get; set; }
        public Stopwatch _Execution_Time_Compute_Space_Kpi_Data_Weekly { get; set; }
        public Stopwatch _Execution_Time_Compute_Space_Kpi_Data_Monthly { get; set; }
        public Stopwatch _Execution_Time_Edit_Space_Kpi_Data_List_Unique_By_RECORD_DATE_KPI_ID_TIMESPAN { get; set; }
        public Stopwatch _Execution_Time_Insert_Space_Kpi_Data_List { get; set; }
        public Stopwatch _Execution_Time_Delete_Space_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Delete_Alert { get; set; }
        public Stopwatch _Execution_Time_Edit_Alert_List { get; set; }
        public Stopwatch _Execution_Time_Get_Alerts_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Alerts_By_Where_Count { get; set; }
        public Stopwatch _Execution_Time_Get_Alerts_For_Levels { get; set; }
        public Stopwatch _Execution_Time_Get_Alerts_Count_For_Levels { get; set; }
        public Stopwatch _Execution_Time_Get_Ext_study_zone_geojson_By_EXT_STUDY_ZONE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Kpi_chart_configuration { get; set; }
        public Stopwatch _Execution_Time_Edit_Kpi_chart_configuration { get; set; }
        public Stopwatch _Execution_Time_Get_GeoData_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_GeoData_By_ORGANIZATION_DATA_SOURCE_KPI_ID_LEVEL_ID_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Businesses_Simple_By_ORGANIZATION_DATA_SOURCE_KPI_ID_LEVEL_ID_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Businesses_By_ORGANIZATION_DATA_SOURCE_KPI_ID_LEVEL_ID_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Bylaw_Complaint_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Public_Event_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_Kpi_Data_Aggregate_Sum { get; set; }
        public Stopwatch _Execution_Time_Get_Area_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Area_Kpi_Data_Aggregate_Sum { get; set; }
        public Stopwatch _Execution_Time_Get_Site_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Site_Kpi_Data_Aggregate_Sum { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_Kpi_Data_Aggregate_Sum { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_Kpi_Data_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_Kpi_Data_Aggregate_Sum { get; set; }
        public Stopwatch _Execution_Time_Get_Site_Kpi_Dialog_Data { get; set; }
        public Stopwatch _Execution_Time_Get_Area_Kpi_Dialog_Data { get; set; }
        public Stopwatch _Execution_Time_Get_District_Kpi_Dialog_Data { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_Kpi_Dialog_Data { get; set; }
        public Stopwatch _Execution_Time_Get_Floor_Kpi_Dialog_Data { get; set; }
        public Stopwatch _Execution_Time_Get_Intersection_Kpi_Dialog_Data { get; set; }
        public Stopwatch _Execution_Time_Get_Bylaw_Complaint_List { get; set; }
        public Stopwatch _Execution_Time_Get_Business_List { get; set; }
        public Stopwatch _Execution_Time_Get_Public_Event_List { get; set; }
        public Stopwatch _Execution_Time_Get_Visitor_Origins { get; set; }
        public Stopwatch _Execution_Time_Get_Latest_Visitor_Count_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Business_Trendline { get; set; }
        public Stopwatch _Execution_Time_Get_Bylaw_Complaints_Trendline { get; set; }
        public Stopwatch _Execution_Time_Get_Public_Events_Trendline { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_Data_Access { get; set; }
        public Stopwatch _Execution_Time_Edit_Organization_Data_Access { get; set; }
        public Stopwatch _Execution_Time_Get_User_Data_Access { get; set; }
        public Stopwatch _Execution_Time_Edit_User_Data_Access { get; set; }
        public Stopwatch _Execution_Time_Get_Latest_Wifi_signals { get; set; }
        public Stopwatch _Execution_Time_Get_Wifi_signals { get; set; }
        public Stopwatch _Execution_Time_Delete_Wifi_signal { get; set; }
        public Stopwatch _Execution_Time_Edit_Wifi_signal_List { get; set; }
        public Stopwatch _Execution_Time_Get_And_Save_Wifi_Signal_From_Api { get; set; }
        public Stopwatch _Execution_Time_Get_Strongest_Wifi_signal { get; set; }
        public Stopwatch _Execution_Time_Compute_Wifi_Signal_Space_Kpi_Data_Hourly { get; set; }
        public Stopwatch _Execution_Time_Get_Latest_Wifi_signal_alerts { get; set; }
        public Stopwatch _Execution_Time_Get_Wifi_signal_alerts { get; set; }
        public Stopwatch _Execution_Time_Delete_Wifi_signal_alert { get; set; }
        public Stopwatch _Execution_Time_Edit_Wifi_signal_alert_List { get; set; }
        public Stopwatch _Execution_Time_Get_Most_Wifi_signal_Count_Per_Space_asset { get; set; }
        public Stopwatch _Execution_Time_Update_Wifi_signal { get; set; }
        #endregion
        #region BLC_OnPreEvent_General_Monitoring
        public void BLC_OnPreEvent_General_Monitoring(string i_MethodName, string i_Method_Params, bool is_Cached)
        {
            #region Body Section.
            var oStopWatch = (Stopwatch)Props.Get_Prop_Value(this, string.Format("_Execution_Time_{0}", i_MethodName));
            Props.Set_Prop_Value(this, string.Format("_Execution_Time_{0}", i_MethodName), Stopwatch.StartNew());
            #endregion
        }
        #endregion
        #region BLC_OnPostEvent_General_Monitoring
        public void BLC_OnPostEvent_General_Monitoring(string i_MethodName, string i_Method_Params, bool is_Cached)
        {
            Task.Run(() =>
            {
                if (i_MethodName != "Edit_Method_run")
                {
                    #region Declaration And Initialization Section.
                    Service_Mesh.Method_run oMethod_run = new Service_Mesh.Method_run();
                    #endregion
                    #region Body Section.
                    Props.Set_Properties_Default_Value(oMethod_run);
                    oMethod_run.METHOD_RUN_ID = -1;
                    oMethod_run.IS_CACHED = is_Cached;
                    oMethod_run.METHOD_NAME = i_MethodName;
                    oMethod_run.RUN_HOUR = DateTime.Now.Hour;
                    oMethod_run.METHOD_PARAMS = i_Method_Params;
                    oMethod_run.RUN_MINUTE = DateTime.Now.Minute;
                    oMethod_run.RUN_SECOND = DateTime.Now.Second;
                    oMethod_run.RUN_DATE = Tools.GetDateString(DateTime.Today);
                    // Calculate Execution time
                    if (Props.Get_Prop_Value(this, string.Format("_Execution_Time_{0}", i_MethodName)) != null)
                    {
                        var oStopWatch = (Stopwatch)Props.Get_Prop_Value(this, string.Format("_Execution_Time_{0}", i_MethodName));
                        oStopWatch.Stop();
                        var elapsedMs = oStopWatch.ElapsedMilliseconds;
                        oMethod_run.EXECUTION_TIME = (int)elapsedMs;
                    }
                    this._service_mesh.Edit_Method_run(oMethod_run);
                    #endregion
                }
            });
        }
        #endregion
        #region Initialize_Monitoring_Mechanism
        public void Initialize_Monitoring_Mechanism()
        {
            #region Body Section.
            if (ConfigurationManager.AppSettings["ENABLE_MONITORING"] != null && ConfigurationManager.AppSettings["ENABLE_MONITORING"] == "1")
            {
                this.OnPreEvent_General += new PreEvent_Handler_General(BLC_OnPreEvent_General_Monitoring);
                this.OnPostEvent_General += new PostEvent_Handler_General(BLC_OnPostEvent_General_Monitoring);
            }
            #endregion
        }
        #endregion
    }
}