using System;
using SmartrTools;
using System.Diagnostics;
using System.Configuration;
using System.Threading.Tasks;

namespace BLC
{
    public partial class BLC
    {
        #region StopWatch properties
        public Stopwatch _Execution_Time_Get_Site_view_By_SITE_VIEW_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_REMOVED_EXTRUSION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_ENTITY_VIEW_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Top_level_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_KPI_USER_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_KPI_USER_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_LEVEL_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_USER_DISTRICTNEX_MODULE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_KPI_USER_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_DISTRICT_VIEW_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_AREA_VIEW_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_SETUP_CATEGORY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_ORGANIZATION_RELATION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_KPI_USER_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_USER_THEME_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_REGION_VIEW_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_SITE_VIEW_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_REMOVED_EXTRUSION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_ENTITY_VIEW_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_KPI_USER_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_KPI_USER_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_LEVEL_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_USER_DISTRICTNEX_MODULE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_KPI_USER_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_DISTRICT_VIEW_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_AREA_VIEW_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_ORGANIZATION_RELATION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_KPI_USER_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_SITE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_USER_THEME_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_REGION_VIEW_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_SITE_VIEW_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_REMOVED_EXTRUSION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_ENTITY_VIEW_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Top_level_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_KPI_USER_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_KPI_USER_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_LEVEL_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_USER_DISTRICTNEX_MODULE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_KPI_USER_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_DISTRICT_VIEW_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_AREA_VIEW_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_SETUP_CATEGORY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_ORGANIZATION_RELATION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_KPI_USER_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_SITE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_USER_THEME_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_REGION_VIEW_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_SITE_VIEW_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_REMOVED_EXTRUSION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_ENTITY_VIEW_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_KPI_USER_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_KPI_USER_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_LEVEL_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_USER_DISTRICTNEX_MODULE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_KPI_USER_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_DISTRICT_VIEW_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_AREA_VIEW_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_ORGANIZATION_RELATION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_KPI_USER_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_SITE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_USER_THEME_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_REGION_VIEW_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Top_level_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Top_level_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_ORGANIZATION_LEVEL_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_ID_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_DISTRICTNEX_MODULE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_SETUP_CATEGORY_NAME_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_PARENT_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_CHILD_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_VALUE { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USERNAME_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_EMAIL_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_IS_RECEIVE_EMAIL { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_IS_ACTIVE_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_ORGANIZATION_THEME_ID { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_VIEW_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_SITE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_DATA_LEVEL_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_VIEW_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_ENTITY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_SITE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_TOP_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_ORGANIZATION_LEVEL_ACCESS_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_DATA_LEVEL_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_ID_DATA_LEVEL_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_DISTRICTNEX_MODULE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_VIEW_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_TOP_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_VIEW_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_PARENT_ORGANIZATION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_CHILD_ORGANIZATION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_VALUE_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_TOP_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_TOP_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USERNAME_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_EMAIL_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_ORGANIZATION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_IS_RECEIVE_EMAIL_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_OWNER_ID_IS_ACTIVE_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_AREA_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_DISTRICT_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_TOP_LEVEL_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_USER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_ORGANIZATION_THEME_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_OWNER_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_REGION_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_VIEW_TYPE_SETUP_ID_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_OWNER_ID_IS_DELETED_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_VIEW_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_SITE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_DATA_LEVEL_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_VIEW_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_ENTITY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_SITE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_ORGANIZATION_LEVEL_ACCESS_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_DATA_LEVEL_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_DISTRICTNEX_MODULE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_VIEW_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_VIEW_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_PARENT_ORGANIZATION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_CHILD_ORGANIZATION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_ORGANIZATION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_TOP_LEVEL_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_USER_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_ORGANIZATION_THEME_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_REGION_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_VIEW_TYPE_SETUP_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_VIEW_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_SITE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_DATA_LEVEL_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_VIEW_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_ENTITY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_SITE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_ENTITY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_SITE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_TOP_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_ENTITY_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_ORGANIZATION_LEVEL_ACCESS_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_DATA_LEVEL_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_DISTRICTNEX_MODULE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ENTITY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_VIEW_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_TOP_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_VIEW_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_SITE_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_PARENT_ORGANIZATION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_CHILD_ORGANIZATION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_SETUP_CATEGORY_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_TOP_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_TOP_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_USER_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_ORGANIZATION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_AREA_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_DISTRICT_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_TOP_LEVEL_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_USER_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_ORGANIZATION_THEME_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_REGION_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_VIEW_TYPE_SETUP_ID_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Top_level_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_category_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_Where_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_Where_In_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_view_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Removed_extrusion_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_view_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_user_access_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_user_access_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_level_access_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_districtnex_module_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_kpi_user_access_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_view_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_view_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_relation_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Area_kpi_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_District_kpi_user_access_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Site_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_User_theme_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Get_Region_view_By_Where_In_List_Adv { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_view { get; set; }
        public Stopwatch _Execution_Time_Delete_Removed_extrusion { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_view { get; set; }
        public Stopwatch _Execution_Time_Delete_Top_level { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_User_level_access { get; set; }
        public Stopwatch _Execution_Time_Delete_User_districtnex_module { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Delete_District_view { get; set; }
        public Stopwatch _Execution_Time_Delete_Area { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_view { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_category { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_relation { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi { get; set; }
        public Stopwatch _Execution_Time_Delete_Region { get; set; }
        public Stopwatch _Execution_Time_Delete_District { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Delete_User { get; set; }
        public Stopwatch _Execution_Time_Delete_Site { get; set; }
        public Stopwatch _Execution_Time_Delete_User_theme { get; set; }
        public Stopwatch _Execution_Time_Delete_Region_view { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_view_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Removed_extrusion_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Removed_extrusion_By_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Removed_extrusion_By_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Removed_extrusion_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_view_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Top_level_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Top_level_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_By_ENTITY_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_level_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_level_access_By_ORGANIZATION_LEVEL_ACCESS_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_level_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_level_access_By_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_level_access_By_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_level_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_User_level_access_By_USER_ID_DATA_LEVEL_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_districtnex_module_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_districtnex_module_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_districtnex_module_By_DISTRICTNEX_MODULE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_districtnex_module_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_ENTITY_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Entity_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_District_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_view_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_view_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_kpi_By_SITE_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_category_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_category_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_category_By_SETUP_CATEGORY_NAME_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_relation_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_relation_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_relation_By_PARENT_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_relation_By_CHILD_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Organization_relation_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_By_SETUP_CATEGORY_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_By_SETUP_CATEGORY_ID_VALUE { get; set; }
        public Stopwatch _Execution_Time_Delete_Setup_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Area_kpi_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Region_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Region_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Region_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_District_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_District_kpi_user_access_By_ORGANIZATION_DATA_SOURCE_KPI_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_USERNAME_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_EMAIL_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_USER_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_ORGANIZATION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_IS_RECEIVE_EMAIL { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_User_By_OWNER_ID_IS_ACTIVE_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_AREA_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_DISTRICT_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Site_By_TOP_LEVEL_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_theme_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_theme_By_USER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_theme_By_ORGANIZATION_THEME_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_User_theme_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Delete_Region_view_By_OWNER_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Region_view_By_REGION_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Region_view_By_VIEW_TYPE_SETUP_ID { get; set; }
        public Stopwatch _Execution_Time_Delete_Region_view_By_OWNER_ID_IS_DELETED { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_view { get; set; }
        public Stopwatch _Execution_Time_Edit_Removed_extrusion { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_view { get; set; }
        public Stopwatch _Execution_Time_Edit_Top_level { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity { get; set; }
        public Stopwatch _Execution_Time_Edit_District_kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_User_level_access { get; set; }
        public Stopwatch _Execution_Time_Edit_User_districtnex_module { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Edit_District_view { get; set; }
        public Stopwatch _Execution_Time_Edit_Area { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_view { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_Setup_category { get; set; }
        public Stopwatch _Execution_Time_Edit_Organization_relation { get; set; }
        public Stopwatch _Execution_Time_Edit_Setup { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_kpi { get; set; }
        public Stopwatch _Execution_Time_Edit_Region { get; set; }
        public Stopwatch _Execution_Time_Edit_District { get; set; }
        public Stopwatch _Execution_Time_Edit_District_kpi_user_access { get; set; }
        public Stopwatch _Execution_Time_Edit_User { get; set; }
        public Stopwatch _Execution_Time_Edit_Site { get; set; }
        public Stopwatch _Execution_Time_Edit_User_theme { get; set; }
        public Stopwatch _Execution_Time_Edit_Region_view { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_view_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Removed_extrusion_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_view_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Top_level_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_kpi_user_access_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_kpi_user_access_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_List { get; set; }
        public Stopwatch _Execution_Time_Edit_District_kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_User_level_access_List { get; set; }
        public Stopwatch _Execution_Time_Edit_User_districtnex_module_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Entity_kpi_user_access_List { get; set; }
        public Stopwatch _Execution_Time_Edit_District_view_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_view_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Setup_category_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Organization_relation_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Setup_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Area_kpi_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Region_List { get; set; }
        public Stopwatch _Execution_Time_Edit_District_List { get; set; }
        public Stopwatch _Execution_Time_Edit_District_kpi_user_access_List { get; set; }
        public Stopwatch _Execution_Time_Edit_User_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Site_List { get; set; }
        public Stopwatch _Execution_Time_Edit_User_theme_List { get; set; }
        public Stopwatch _Execution_Time_Edit_Region_view_List { get; set; }
        public Stopwatch _Execution_Time_Get_Organization_URL_By_Setup_Value { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_ID_By_Value { get; set; }
        public Stopwatch _Execution_Time_Get_Setup_By_Setup_ID_From_Setup_Category_List { get; set; }
        public Stopwatch _Execution_Time_Create_User { get; set; }
        public Stopwatch _Execution_Time_Restore_User { get; set; }
        public Stopwatch _Execution_Time_Get_Admin_Data { get; set; }
        public Stopwatch _Execution_Time_Change_Password { get; set; }
        public Stopwatch _Execution_Time_Modify_User_Details { get; set; }
        public Stopwatch _Execution_Time_Permanently_Delete_User { get; set; }
        public Stopwatch _Execution_Time_Schedule_User_for_Delete { get; set; }
        public Stopwatch _Execution_Time_Edit_User_Details { get; set; }
        public Stopwatch _Execution_Time_Change_User_Password { get; set; }
        public Stopwatch _Execution_Time_Get_User_Accessible_Data { get; set; }
        public Stopwatch _Execution_Time_Get_User_Accessible_Level_List { get; set; }
        public Stopwatch _Execution_Time_Get_User_Accessible_Data_With_Level_List { get; set; }
        public Stopwatch _Execution_Time_Get_Level_Data { get; set; }
        public Stopwatch _Execution_Time_Get_Dimension_Index_With_Simple_Upper_Level { get; set; }
        public Stopwatch _Execution_Time_Edit_User_Walkthrough { get; set; }
        public Stopwatch _Execution_Time_Check_User_Deletion_Status { get; set; }
        public Stopwatch _Execution_Time_Send_Support_Email { get; set; }
        public Stopwatch _Execution_Time_Get_Entity_Intersection_List { get; set; }
        public Stopwatch _Execution_Time_Get_Initial_Data { get; set; }
        public Stopwatch _Execution_Time_Get_List_Organization_with_Accessible_Top_Levels { get; set; }
        public Stopwatch _Execution_Time_Get_Dimension_index_By_Where { get; set; }
        public Stopwatch _Execution_Time_Insert_Dimension_index_List { get; set; }
        public Stopwatch _Execution_Time_Delete_Dimension_index_By_Where { get; set; }
        public Stopwatch _Execution_Time_Get_District_geojson_By_DISTRICT_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Area_geojson_By_AREA_ID_List { get; set; }
        public Stopwatch _Execution_Time_Get_Site_geojson_By_SITE_ID_List { get; set; }
        #endregion
        #region BLC_OnPreEvent_General_Monitoring
        public void BLC_OnPreEvent_General_Monitoring(string i_MethodName, string i_Method_Params, bool is_Cached)
        {
            #region Body Section.
            var oStopWatch = (Stopwatch)Props.Get_Prop_Value(this, string.Format("_Execution_Time_{0}", i_MethodName));
            Props.Set_Prop_Value(this, string.Format("_Execution_Time_{0}", i_MethodName), Stopwatch.StartNew());
            #endregion
        }
        #endregion
        #region BLC_OnPostEvent_General_Monitoring
        public void BLC_OnPostEvent_General_Monitoring(string i_MethodName, string i_Method_Params, bool is_Cached)
        {
            Task.Run(() =>
            {
                if (i_MethodName != "Edit_Method_run")
                {
                    #region Declaration And Initialization Section.
                    Service_Mesh.Method_run oMethod_run = new Service_Mesh.Method_run();
                    #endregion
                    #region Body Section.
                    Props.Set_Properties_Default_Value(oMethod_run);
                    oMethod_run.METHOD_RUN_ID = -1;
                    oMethod_run.IS_CACHED = is_Cached;
                    oMethod_run.METHOD_NAME = i_MethodName;
                    oMethod_run.RUN_HOUR = DateTime.Now.Hour;
                    oMethod_run.METHOD_PARAMS = i_Method_Params;
                    oMethod_run.RUN_MINUTE = DateTime.Now.Minute;
                    oMethod_run.RUN_SECOND = DateTime.Now.Second;
                    oMethod_run.RUN_DATE = Tools.GetDateString(DateTime.Today);
                    // Calculate Execution time
                    if (Props.Get_Prop_Value(this, string.Format("_Execution_Time_{0}", i_MethodName)) != null)
                    {
                        var oStopWatch = (Stopwatch)Props.Get_Prop_Value(this, string.Format("_Execution_Time_{0}", i_MethodName));
                        oStopWatch.Stop();
                        var elapsedMs = oStopWatch.ElapsedMilliseconds;
                        oMethod_run.EXECUTION_TIME = (int)elapsedMs;
                    }
                    this._service_mesh.Edit_Method_run(oMethod_run);
                    #endregion
                }
            });
        }
        #endregion
        #region Initialize_Monitoring_Mechanism
        public void Initialize_Monitoring_Mechanism()
        {
            #region Body Section.
            if (ConfigurationManager.AppSettings["ENABLE_MONITORING"] != null && ConfigurationManager.AppSettings["ENABLE_MONITORING"] == "1")
            {
                this.OnPreEvent_General += new PreEvent_Handler_General(BLC_OnPreEvent_General_Monitoring);
                this.OnPostEvent_General += new PostEvent_Handler_General(BLC_OnPostEvent_General_Monitoring);
            }
            #endregion
        }
        #endregion
    }
}