apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.api.backendServiceName }}-reverse-proxy-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    chartVersion: {{ .Chart.Version }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    alb.ingress.kubernetes.io/scheme: "{{ .Values.scheme }}"
    alb.ingress.kubernetes.io/listen-ports: '{{ .Values.listen_ports }}'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.api.certificateARN }}"
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{{ .Values.ssl_redirect }}'
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.api.backendServiceName }}-reverse-proxy
            port:
              number: {{ .Values.api.backendServicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.websockets.backendServiceName }}-reverse-proxy-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    chartVersion: {{ .Chart.Version }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    alb.ingress.kubernetes.io/scheme: "{{ .Values.scheme }}"
    alb.ingress.kubernetes.io/listen-ports: '{{ .Values.listen_ports }}'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.websockets.certificateARN }}"
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{{ .Values.ssl_redirect }}'
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.websockets.backendServiceName }}-reverse-proxy
            port:
              number: {{ .Values.websockets.backendServicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.clientsUI.backendServiceName }}-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    chartVersion: {{ .Chart.Version }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    alb.ingress.kubernetes.io/scheme: "{{ .Values.scheme }}"
    alb.ingress.kubernetes.io/listen-ports: '{{ .Values.listen_ports }}'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.clientsUI.certificateARN }}"
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{{ .Values.ssl_redirect }}'
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.clientsUI.backendServiceName }}
            port:
              number: {{ .Values.clientsUI.backendServicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.adminUI.backendServiceName }}-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    chartVersion: {{ .Chart.Version }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    alb.ingress.kubernetes.io/scheme: "{{ .Values.scheme }}"
    alb.ingress.kubernetes.io/listen-ports: '{{ .Values.listen_ports }}'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.adminUI.certificateARN }}"
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{{ .Values.ssl_redirect }}'
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.adminUI.backendServiceName }}
            port:
              number: {{ .Values.adminUI.backendServicePort }}
