apiVersion: skaffold/v4beta2
kind: Config

profiles:
- name: dev
  deploy:
    statusCheck: false
    helm:
      releases:
      - name: metrics-server
        remoteChart: metrics-server
        repo: https://kubernetes-sigs.github.io/metrics-server
        createNamespace: true
        namespace: metrics-server
      - name: aws-efs-csi-driver
        remoteChart: aws-efs-csi-driver
        repo: https://kubernetes-sigs.github.io/aws-efs-csi-driver
        namespace: kube-system
      - name: aws-ebs-csi-driver
        remoteChart: aws-ebs-csi-driver
        repo: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
        namespace: kube-system
      - name: goldilocks
        remoteChart: goldilocks
        repo: https://charts.fairwinds.com/stable
        namespace: goldilocks
        createNamespace: true
        setValues:
          vpa:
            enabled: true
      - name: districtnex-dev
        chartPath: helm
        createNamespace: true
        namespace: districtnex-dev
        valuesFiles:
        - helm/targets/dev.yaml
        packaged:
          version: "3.1.3"
          appVersion: "3.1.3"
- name: demo
  deploy:
    statusCheck: false
    helm:
      releases:
      - name: metrics-server
        remoteChart: metrics-server
        repo: https://kubernetes-sigs.github.io/metrics-server
        createNamespace: true
        namespace: metrics-server
      - name: aws-efs-csi-driver
        remoteChart: aws-efs-csi-driver
        repo: https://kubernetes-sigs.github.io/aws-efs-csi-driver
        namespace: kube-system
      - name: aws-ebs-csi-driver
        remoteChart: aws-ebs-csi-driver
        repo: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
        namespace: kube-system
      - name: goldilocks
        remoteChart: goldilocks
        repo: https://charts.fairwinds.com/stable
        namespace: goldilocks
        createNamespace: true
        setValues:
          vpa:
            enabled: true
      - name: districtnex-demo
        chartPath: helm
        createNamespace: true
        namespace: districtnex-demo
        valuesFiles:
        - helm/targets/demo.yaml
        packaged:
          version: "3.1.3"
          appVersion: "3.1.3"
