apiVersion: v2
name: districtnex
description: Umbrella chart for districtnex microservices
type: application
version: 3.1.3

dependencies:

############## dependencies ##############

- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.9.4
  condition: mongodb.enabled
# - name: redis
#   repository: https://charts.bitnami.com/bitnami
#   version: 17.9.4
#   condition: redis.enabled

############## microservices ##############

- name: region-management-webapi
  repository: "file://charts/region-management-webapi"
  version: 3.1.3
  condition: region-management-webapi.enabled
- name: method-monitoring-webapi
  repository: "file://charts/method-monitoring-webapi"
  version: 3.1.3
  condition: method-monitoring-webapi.enabled
- name: api-gateway
  repository: "file://charts/api-gateway"
  version: 3.1.3
  condition: api-gateway.enabled
- name: security-dimension-webapi
  repository: "file://charts/security-dimension-webapi"
  version: 3.1.3
  condition: security-dimension-webapi.enabled
- name: admin-ui
  repository: "file://charts/admin-ui"
  version: 3.1.3
  condition: admin-ui.enabled
- name: smart-living-dimension-webapi
  repository: "file://charts/smart-living-dimension-webapi"
  version: 3.1.3
  condition: smart-living-dimension-webapi.enabled
- name: signalr-realtime-server-reverse-proxy
  repository: "file://charts/signalr-realtime-server-reverse-proxy"
  version: 3.1.3
  condition: signalr-realtime-server-reverse-proxy.enabled
- name: correlation-calculation-webapi
  repository: "file://charts/correlation-calculation-webapi"
  version: 3.1.3
  condition: correlation-calculation-webapi.enabled
- name: area-management-webapi
  repository: "file://charts/area-management-webapi"
  version: 3.1.3
  condition: area-management-webapi.enabled
- name: entity-management-webapi
  repository: "file://charts/entity-management-webapi"
  version: 3.1.3
  condition: entity-management-webapi.enabled
- name: user-management-webapi
  repository: "file://charts/user-management-webapi"
  version: 3.1.3
  condition: user-management-webapi.enabled
- name: api-gateway-reverse-proxy
  repository: "file://charts/api-gateway-reverse-proxy"
  version: 3.1.3
  condition: api-gateway-reverse-proxy.enabled
- name: settings-management-webapi
  repository: "file://charts/settings-management-webapi"
  version: 3.1.3
  condition: settings-management-webapi.enabled
- name: signalr-realtime-server
  repository: "file://charts/signalr-realtime-server"
  version: 3.1.3
  condition: signalr-realtime-server.enabled
- name: user-authentication-webapi
  repository: "file://charts/user-authentication-webapi"
  version: 3.1.3
  condition: user-authentication-webapi.enabled
- name: platform-logging-webapi
  repository: "file://charts/platform-logging-webapi"
  version: 3.1.3
  condition: platform-logging-webapi.enabled
- name: top-level-management-webapi
  repository: "file://charts/top-level-management-webapi"
  version: 3.1.3
  condition: top-level-management-webapi.enabled
- name: mobility-dimension-webapi
  repository: "file://charts/mobility-dimension-webapi"
  version: 3.1.3
  condition: mobility-dimension-webapi.enabled
- name: kpi-management-webapi
  repository: "file://charts/kpi-management-webapi"
  version: 3.1.3
  condition: kpi-management-webapi.enabled
- name: reporting-webapi
  repository: "file://charts/reporting-webapi"
  version: 3.1.3
  condition: reporting-webapi.enabled
- name: dimension-management-webapi
  repository: "file://charts/dimension-management-webapi"
  version: 3.1.3
  condition: dimension-management-webapi.enabled
- name: space-management-webapi
  repository: "file://charts/space-management-webapi"
  version: 3.1.3
  condition: space-management-webapi.enabled
- name: floor-management-webapi
  repository: "file://charts/floor-management-webapi"
  version: 3.1.3
  condition: floor-management-webapi.enabled
- name: kpi-extraction-engine-webapi
  repository: "file://charts/kpi-extraction-engine-webapi"
  version: 3.1.3
  condition: kpi-extraction-engine-webapi.enabled
- name: video-ai-engine-management-webapi
  repository: "file://charts/video-ai-engine-management-webapi"
  version: 3.1.3
  condition: video-ai-engine-management-webapi.enabled
- name: cloud-interface-webapi
  repository: "file://charts/cloud-interface-webapi"
  version: 3.1.3
  condition: cloud-interface-webapi.enabled
- name: file-management-webapi
  repository: "file://charts/file-management-webapi"
  version: 3.1.3
  condition: file-management-webapi.enabled
- name: sustainability-dimension-webapi
  repository: "file://charts/sustainability-dimension-webapi"
  version: 3.1.3
  condition: sustainability-dimension-webapi.enabled
- name: asset-management-webapi
  repository: "file://charts/asset-management-webapi"
  version: 3.1.3
  condition: asset-management-webapi.enabled
- name: client-ui
  repository: "file://charts/client-ui"
  version: 3.1.3
  condition: client-ui.enabled
- name: site-management-webapi
  repository: "file://charts/site-management-webapi"
  version: 3.1.3
  condition: site-management-webapi.enabled
- name: organization-management-webapi
  repository: "file://charts/organization-management-webapi"
  version: 3.1.3
  condition: organization-management-webapi.enabled
- name: insights-management-webapi
  repository: "file://charts/insights-management-webapi"
  version: 3.1.3
  condition: insights-management-webapi.enabled
- name: shareview-webapi
  repository: "file://charts/shareview-webapi"
  version: 3.1.3
  condition: shareview-webapi.enabled
- name: district-management-webapi
  repository: "file://charts/district-management-webapi"
  version: 3.1.3
  condition: district-management-webapi.enabled
- name: mobility-dimension-cron
  repository: "file://charts/mobility-dimension-cron"
  version: 3.1.3
  condition: mobility-dimension-cron.enabled
- name: bylaw-complaints-cron
  repository: "file://charts/bylaw-complaints-cron"
  version: 3.1.3
  condition: bylaw-complaints-cron.enabled
- name: security-dimension-cron
  repository: "file://charts/security-dimension-cron"
  version: 3.1.3
  condition: security-dimension-cron.enabled
- name: video-ai-engine-management-cron
  repository: "file://charts/video-ai-engine-management-cron"
  version: 3.1.3
  condition: video-ai-engine-management-cron.enabled
- name: businesses-cron
  repository: "file://charts/businesses-cron"
  version: 3.1.3
  condition: businesses-cron.enabled
- name: data-retention-cron
  repository: "file://charts/data-retention-cron"
  version: 3.1.3
  condition: data-retention-cron.enabled
- name: smart-living-dimension-cron
  repository: "file://charts/smart-living-dimension-cron"
  version: 3.1.3
  condition: smart-living-dimension-cron.enabled
- name: telus-api-data-1-cron
  repository: "file://charts/telus-api-data-1-cron"
  version: 3.1.3
  condition: telus-api-data-1-cron.enabled
- name: telus-api-data-2-cron
  repository: "file://charts/telus-api-data-2-cron"
  version: 3.1.3
  condition: telus-api-data-2-cron.enabled
- name: public-events-cron
  repository: "file://charts/public-events-cron"
  version: 3.1.3
  condition: public-events-cron.enabled
- name: sustainability-dimension-cron
  repository: "file://charts/sustainability-dimension-cron"
  version: 3.1.3
  condition: sustainability-dimension-cron.enabled
- name: wifi-signal-cron
  repository: "file://charts/wifi-signal-cron"
  version: 3.1.3
  condition: wifi-signal-cron.enabled
- name: data-creation-cron
  repository: "file://charts/data-creation-cron"
  version: 3.1.3
  condition: data-creation-cron.enabled
- name: mgob
  repository: "file://charts/mgob"
  version: 3.1.3
  condition: mgob.enabled
- name: ingress-controller
  repository: "file://charts/ingress-controller"
  version: 3.1.3
  condition: ingress-controller.enabled
