name: Build and Push Docker Images

on:
  push:
    tags:
      - "districtnex-v*"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push UI
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: samerahmad01/districtnex:${{ github.ref_name }}-ui
          context: DistrictNex_UI
          dockerfile: Dockerfile

  build-and-push-admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Admin
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: samerahmad01/districtnex:${{ github.ref_name }}-admin
          context: DistrictNex_Admin
          dockerfile: Dockerfile
