name: Sync to GitLab

on:
  push:
    tags:
      - "*"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get install git -y

      # - name: Configure Git
      #   run: |
      #     git config user.name "samer.ahmad"
      #     git config user.email "sameraliahmad01@gmail.com"

      - name: Push to GitLab
        run: |
          git remote add gitlab https://gitlab.com/test2604520/test.git
          git config credential.helper 'store --file=.git/credentials'
          echo "https://oauth2:$glpat-VDXcyCAhdgsizgsVN_Kp@gitlab.com/test2604520/test.git" > .git/credentials
          git push gitlab HEAD:main
