name: Sync with GitLab

on:
  push:
    tags:
      - "*"

jobs:
  sync_with_gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "samer.ahmad"
          git config user.email "sameraliahmad01@gmail.com"

      - name: Sync with GitLab
        run: |
          git remote add gitlab https://gitlab.com/test2604520/test.git
          git config --global credential.helper store
          echo "https://oauth2:glpat-VDXcyCAhdgsizgsVN_Kp@gitlab.com/test2604520/test.git" >> ~/.git-credentials
          git add .
          git commit -m "test"
          git push --all gitlab
